### ISSUE TITLE
Error adding customer

### ISSUE THREAD

**Issue by ccjcan** [sabbir2609/plantx-be#2]
Hi, great work on this code, downloaded and started to experiment.

I found an error: 
- When using Admin I try adding Customer, click the + to add a new user. The issue is that the form is asking for an user id when I believe you are using email for authentication (on admin). I get an error when trying to add the new user.

UNIQUE constraint failed: users_user.email

Request Method: 	POST
Request URL: 	http://127.0.0.1:8000/admin/users/user/add/?_to_field=id&_popup=1
Django Version: 	5.0.7
Exception Type: 	IntegrityError
Exception Value: 	

UNIQUE constraint failed: users_user.email

**Comment by sabbir2609** [comment]
Thank you for finding out the problem. I've fixed it. Please don't hesitate to let me know if you have any other errors!
